### ISSUE TITLE
BracketHighlighter AttributeError on OS X

### ISSUE THREAD

**Issue by N4M3Z** [facelessuser/BracketHighlighter#232]
I am getting `AttributeError: type object 'BhEventMgr'` in Sublime Text 3065 on OS X Yosemite:
```
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 287, in on_selection_modified
    callback.on_selection_modified(v)
  File "bh_core in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 837, in on_selection_modified
  File "bh_core in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 854, in ignore_event
AttributeError: type object 'BhEventMgr' has no attribute 'ignore_all'
```
I tried reinstalling BracketHighlighter, didn't help. Is this perhaps a plugin incompatibility?

**Comment by facelessuser** [comment]
It's actually a problem when the package gets disabled (by Package Control or whatever). Restarting Sublime should get it working again.  This is an issue that was pointed out to me a number of days ago.  I just posted a new release that re-worked thread stuff and should fix this: [`ST3 2.4.3`](https://github.com/facelessuser/BracketHighlighter/releases/tag/st3-2.4.3).  Package Control should see it within the hour.  You can update then via Package Control, and probably a restart will be required.

**Comment by N4M3Z** [comment]
Restarting Sublime did not fix the issue on my end given the current version of BracketHighlighter. I will wait for the update from Package Control and let you know. As far as I can tell, functionality of the plugin is not affected.

**Comment by facelessuser** [comment]
Wait, are you on ST2?  If you are on ST2, no fix is coming.  I just checked, and on ST3 `BhEventMgr` was renamed to `BhThreadMgr` and my recent fix just removed that.  If you are on ST2, I don't actively support that branch anymore.  If you are on ST3 and seeing that error, you are either on an old BH revision, or Package Control installed the wrong branch.

**Comment by N4M3Z** [comment]
ST3, weird. How can I tell the revision/branch?

**Comment by facelessuser** [comment]
Did this get resolved?

**Comment by N4M3Z** [comment]
Well, the issue did not reappear at least.

**Comment by facelessuser** [comment]
Good enough for me.  Maybe it upgraded, but this issue doesn't appear to exist on the latest release, so I will close this.
